[2025-07-16T20:40:03.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-16T20:40:03.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-07-16T20:34:54+00:00 [queued]>
[2025-07-16T20:40:03.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-07-16T20:34:54+00:00 [queued]>
[2025-07-16T20:40:03.285+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-16T20:40:03.297+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-07-16 20:34:54+00:00
[2025-07-16T20:40:03.305+0000] {standard_task_runner.py:63} INFO - Started process 151 to run task
[2025-07-16T20:40:03.308+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-07-16T20:34:54+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpl01rk675']
[2025-07-16T20:40:03.310+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract
[2025-07-16T20:40:03.384+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-07-16T20:34:54+00:00 [running]> on host 105b7bd1729a
[2025-07-16T20:40:03.525+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T20:34:54+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T20:34:54+00:00'
[2025-07-16T20:40:03.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-16T20:40:03.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-16T20:40:03.529+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 25, in extract
    return _extract().to_dict(orient="records")
           ^^^^^^^^^^
  File "/opt/airflow/app/pipeline.py", line 19, in extract
    return pd.read_csv(CSV_PATH)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/input.csv'
[2025-07-16T20:40:03.557+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract, run_id=manual__2025-07-16T20:34:54+00:00, execution_date=20250716T203454, start_date=20250716T204003, end_date=20250716T204003
[2025-07-16T20:40:03.572+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract ([Errno 2] No such file or directory: '/app/data/input.csv'; 151)
[2025-07-16T20:40:03.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-16T20:40:03.629+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T20:40:03.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
